baseurl = "https://peeomid.com/"
disqusShortname = ""
googleAnalytics = "UA-52164311-1"
languageCode = "en-us"
theme = "hugo-creative-portfolio-theme"
title = "Peeomid Profile"
[params]
copyright = "&copy;2016 Osimify"
description = "Peeomid "
email = "luan.nguyensj@gmail.com"
sidebarAbout = ["I am a random person with a wide range of interest:", "Coding, Marketing, Business Process Improvement, Change Management, Personal Development Coaching", "Above all, Sahaja Yoga is my purpose, free and unique way to balance yourself!", "I put my projects here, some are finished, some are in progress, some are... not yet touched. If you want to see something go live faster, do let me know, I may speed it up :P"]
style = "default"
[params.social]
email = "luan.nguyensj@gmail.com"
facebook = "https://www.facebook.com/luantn"
googleplus = "https://plus.google.com/+LuanNguyenPeeomid"
linkedIn = "https://www.linkedin.com/in/luantn"
stackverflow = "http://stackoverflow.com/users/2799495/luan-nguyen"
twitter = "https://twitter.com/peeomid"
[[params.navlinks]]
name = "Home"
url = ""
[[params.navlinks]]
name = "About"
url = "about/"
[[params.navlinks]]
name = "Get in touch"
url = "contact/"
